#!/usr/bin/env python3
"""Update minimal docs/state for BDP-002B.

This script updates repository files only. It does not connect to the database
and does not add SQL migrations.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKBENCH_PATH = ROOT / "docs" / "BUCHANAN_SEMANTIC_WORKBENCH.md"
STATE_PATH = ROOT / "ai_boot" / "BUCHANAN_SYSTEM_STATE.json"

WORKBENCH_MARKER = "## BDP-002B Operator-Facing Evidence Card"
WORKBENCH_SECTION = r"""
## BDP-002B Operator-Facing Evidence Card

BDP-002B consolidates the existing Buchanan `Body without Organs` evidence spine into one operator-facing card generated by a read-only script.

The card may show:

```text
concept identity
canonical Buchanan source metadata
citation-backed passage record status
reviewed concept mention status
source-bound description with authority label
blocked relation status
blocked interpretation status
blocked Buchanan-specific claim status
rights/display rules
```

Required authority labels include:

```text
concept_record
metadata
citation_backed_passage
reviewed_concept_mention
source_bound_description
record_description
rights_display_boundary
blocked_until_reviewed_relation_evidence
blocked_until_governed_interpretation_phase
blocked_until_interpretive_authority_exists
```

Allowed card description:

```text
The database records a restricted, citation-backed Buchanan passage linked to Body without Organs through a reviewed direct concept mention.
```

Blocked card upgrade:

```text
No authorial position, conceptual meaning, relation, interpretation, synthesis, or Buchanan-specific claim may be generated by this card.
```

Rights rule:

```text
passage_text_display = omitted_by_rights_policy
long_quotation_displayed = false
article_reproduction_authorized = false
```

Implementation boundary:

```text
Read script only.
Verifier only.
No SQL migration.
No database mutation.
No frontend work.
No new source, passage, citation, concept mention, relation, interpretation, or generated Buchanan claim.
```
""".strip() + "\n"


def update_workbench() -> None:
    if not WORKBENCH_PATH.exists():
        raise FileNotFoundError(WORKBENCH_PATH)
    text = WORKBENCH_PATH.read_text()
    if WORKBENCH_MARKER not in text:
        if not text.endswith("\n"):
            text += "\n"
        text += "\n" + WORKBENCH_SECTION
        WORKBENCH_PATH.write_text(text)
        print(f"updated {WORKBENCH_PATH}")
    else:
        print(f"unchanged {WORKBENCH_PATH} — BDP-002B section already present")


def update_state() -> None:
    if not STATE_PATH.exists():
        raise FileNotFoundError(STATE_PATH)
    state = json.loads(STATE_PATH.read_text())
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    state["bdp_002b_operator_facing_evidence_card"] = {
        "phase": "BDP-002B",
        "title": "Deliver first usable operator-facing evidence card for Body without Organs",
        "status": "prepared",
        "controlled_slice": "read_only_operator_evidence_card",
        "operator_value": "single-command rights-aware evidence posture readback",
        "database_mutation": False,
        "sql_migration": False,
        "frontend_work": False,
        "new_governance_document": False,
        "read_script": "scripts/read_bdp_002b_bwo_evidence_card.py",
        "verifier": "scripts/verify_bdp_002b_bwo_evidence_card.py",
        "card_authority_labels_required": True,
        "restricted_passage_text_display": "omitted_by_rights_policy",
        "source_bound_description_status": "non_interpretive_record_description",
        "blocked_layers": [
            "concept_relation",
            "interpretation",
            "buchanan_specific_claim",
        ],
        "preserved_invariant": {
            "sources_count": 2,
            "source_candidates_count": 3,
            "passage_candidates_count": 1,
            "passages_count": 2,
            "citations_count": 2,
            "concept_mentions_count": 2,
            "concept_relations_count": 0,
            "interpretations_count": 0,
            "BDP-002B migration_count": 0,
        },
        "philosophy_check": [
            "description_is_not_interpretation",
            "authority_labels_required",
            "restricted_passage_text_omitted",
            "evidence_posture_not_authorial_claim",
            "relations_interpretations_and_claims_remain_blocked",
        ],
        "next_phase_options": [
            "Expand the same Buchanan article evidence spine with another passage.",
            "Begin light ingestion of a second Buchanan source.",
        ],
        "updated_at": now,
    }

    state["current_buchanan_next_step"] = (
        "After BDP-002B verification, choose either another passage from the same Buchanan article "
        "or light ingestion of a second Buchanan source."
    )

    STATE_PATH.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    print(f"updated {STATE_PATH}")


def main() -> int:
    update_workbench()
    update_state()
    print("BDP-002B docs/state update complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
